### ISSUE TITLE
Picking up items does not stack with others

### ISSUE THREAD

**Issue by Valentinovik** [Fuzss/pickupnotifier-fabric#6]
As the title say the items that you collect dont stack with the other ones in your inventory , i have to drop them all and then pick them p again.
Version: PickUpNotifier-v3.2.0-1.18.2-Fabric

**Comment by Fuzss** [comment]
Was the issue resolved?

**Comment by Valentinovik** [comment]
It was not , the problem is from another mod wich i cannot identify.
